dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: pipeline-ubuntu
    managed: false
    groups:
      - debian
  - name: pipeline-rocky
    managed: false
    groups:
      - redhat
provisioner:
  name: ansible
verifier:
  name: testinfra
  directory: tests/
